### ISSUE TITLE
Bug with prefix mfb_icon

### ISSUE THREAD

**Issue by ghost** [joielechong/MaterialFancyButtons#9]
I replace icon with prefix mfb_icon with spesific font dependecies i.e Google Material Design Icon, but i don't see any icon appears in layout rendering on layout xml. please fix it. Thanks
I use app:mfb_icon="@string/gmdi_keyboard_arrow_right"..dont see icon anything...

**Comment by joielechong** [comment]
Now icon appeared in layout editor. Please run the updated sample with version 1.8.8. So sorry for 2 years late :(.
